services:
  backend:
    image: symfony-backend:dev
    build:
      target: dev
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
    restart: "no"
    volumes:
      - ./backend:/var/www/html
